package cn.app.yimirong.model.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "MESSAGE2".
 */
public class Message implements Serializable {

	public String nid;
	public boolean isread = false;
	/**
	 * Not-null value.
	 */
	public String title;
	/**
	 * Not-null value.
	 */
	public String content;
	public String ctime;
	public String onlinetime;
	public String phonetype;
	public String status;
	public String type;
	public String yugaotime;

	public Message() {
	}

	public Message(String nid) {
		this.nid = nid;
	}

	public Message(String nid, Boolean isread, String title, String content, String ctime, String onlinetime, String phonetype, String status, String type, String yugaotime) {
		this.nid = nid;
		this.isread = isread;
		this.title = title;
		this.content = content;
		this.ctime = ctime;
		this.onlinetime = onlinetime;
		this.phonetype = phonetype;
		this.status = status;
		this.type = type;
		this.yugaotime = yugaotime;
	}

	public String getNid() {
		return nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	public boolean getIsread() {
		return isread;
	}

	public void setIsread(boolean isread) {
		this.isread = isread;
	}

	/**
	 * Not-null value.
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the database.
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Not-null value.
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the database.
	 */
	public void setContent(String content) {
		this.content = content;
	}

	public String getCtime() {
		return ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public String getOnlinetime() {
		return onlinetime;
	}

	public void setOnlinetime(String onlinetime) {
		this.onlinetime = onlinetime;
	}

	public String getPhonetype() {
		return phonetype;
	}

	public void setPhonetype(String phonetype) {
		this.phonetype = phonetype;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getYugaotime() {
		return yugaotime;
	}

	public void setYugaotime(String yugaotime) {
		this.yugaotime = yugaotime;
	}

}
